export type LegalBlock = { type: string; text: string };

export const legalPages = {
  "terms": {
    "title": "Terms and Conditions",
    "eyebrow": "Terms of use",
    "sourceUrl": "https://skillcase.in/terms-and-condition",
    "blocks": [
      {
        "type": "h1",
        "text": "Terms and Condition"
      },
      {
        "type": "h1",
        "text": "TERMS OF USE"
      },
      {
        "type": "h3",
        "text": "1. DEFINITIONS"
      },
      {
        "type": "p",
        "text": "1.1. **“Act”** shall mean the Information Technology Act, 2000;"
      },
      {
        "type": "p",
        "text": "1.2. **“Applicable Law(s)”** means all statutes, enactments, acts of legislature or parliament, ordinances, rules, bye-laws, regulations, notifications, policies, directions, directives and orders as such are in effect as of the date hereof or as may be amended, modified, enacted or revoked from time to time hereafter or other governmental restrictions or any similar form of decision of, or determination by any government, statutory authority, tribunal, board, court having jurisdiction over the matter in question in India; 1.3. **“Application”** refers to the web portal (**www.skillcase.in**) by means of which the Company makes its services available."
      },
      {
        "type": "p",
        "text": "1.4. **“Affiliate”** shall mean any Person who directly or indirectly, controls, is controlled by, or is under the common control of the Company. The term “Control” is used in the sense of the possession by a Person or a group of Persons acting in concert, directly or indirectly, of the right to direct or cause the direction of the management and policies of another Person, whether through the board of directors or ownership of voting rights by such other Person, by the Articles of Association, contract or otherwise. A Person or a group of Persons acting in concert shall be deemed to be in control of a body corporate if such Person or group of Persons is in a position to appoint or appoints the majority of the directors of such body corporate. 1.5. **“Authority”** shall mean any union, national, state, local, or other governmental, statutory, administrative, judicial, regulatory or self-regulating authority, agency or instrumentality having jurisdiction over the relevant matter."
      },
      {
        "type": "p",
        "text": "1.6. **“Clause”** refers to the clauses of these Terms of Use."
      },
      {
        "type": "p",
        "text": "1.7. **“User”** shall mean any individual/representatives of entities who avails the Service of the Company through the Application."
      },
      {
        "type": "p",
        "text": "1.8. **“Information”** shall (a) Name of the User; (b) Contact Number, (c) Location of the User, as provided by the User,(d) email (e) educational qualifications and (f) such other information of the User, to the Application."
      },
      {
        "type": "p",
        "text": "1.9. **“Policies”** shall mean and include the Privacy Policy and any other policies of the Company as amended and provided on the Application or communicated to the Users in any other way from time to time."
      },
      {
        "type": "p",
        "text": "1.10. **“Privacy Policy”** refers to the privacy policy published on the Company’s Application [Please attach the privacy policy link here] which forms an integral part of these Terms of Use (defined hereinafter);"
      },
      {
        "type": "p",
        "text": "1.11. **“Terms of Use”** means these Terms of use between the User (defined hereinafter) and the Company (defined hereinafter), governing the User’s use of this Application. 1.12. **“User(s)”** shall mean a user of the Application."
      },
      {
        "type": "h3",
        "text": "2. GENERAL"
      },
      {
        "type": "p",
        "text": "2.1. This document is an electronic record in terms of the Act and the Applicable Laws. This electronic record is generated by a computer system and does not require any physical or digital signatures."
      },
      {
        "type": "p",
        "text": "2.2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 (“Rules”) that require publishing the rules and regulations, privacy policy and terms of use for access or usage of the Application."
      },
      {
        "type": "p",
        "text": "2.3. The owner of the Application is Skillcase Education Private Limited (\"Company\" or “Skillcase”), a company incorporated under the provisions of the Companies Act, 2013, bearing **CIN U85499KA2024PTC185038**, having its registered office at **#1207/343 & 1207/1/343/1, 9th Main, 7th Sector, HSR Layout, Bangalore, Bangalore South, Karnataka, India, 560102** (hereinafter referred to as the as “We”, “Us” or “Our”, which expression shall include Affiliates, successors and permitted assigns)."
      },
      {
        "type": "p",
        "text": "2.4. The Company’s Application is for following services: connecting skilled professionals from India to international opportunities. To simplify hiring by ensuring verified talent, smooth documentation, and end-to-end migration support."
      },
      {
        "type": "p",
        "text": "2.5. For the purposes of these Terms of Use, ‘User’ and wherever the context may require, ‘You’ (or any variation thereof), shall mean any natural or legal person (including any legal heirs, administrators or successors) who has agreed to become a User of the Application by accessing or using the Application."
      },
      {
        "type": "p",
        "text": "2.6. If You are accepting these Terms on behalf of a company, organization, government, or other legal entity, You represent and warrant that You are authorized to do so. 2.7. By mere use of the Application, You agree to be subject to the applicable rules, guidelines, Policies, terms, and conditions and the same shall be deemed to be incorporated into these Terms of Use and be considered as part and parcel of these Terms of Use."
      },
      {
        "type": "p",
        "text": "2.8. ACCESSING, BROWSING OR OTHERWISE USING THE APPLICATION INDICATES YOUR ACCEPTANCE OF ALL THE TERMS AND CONDITIONS IN THESE TERMS OF USE. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE PROCEEDING. YOU DECLARE YOUR WILLINGNESS TO ABIDE AND BE BOUND BY THESE TERMS OF USE THROUGH YOUR USE OF THE APPLICATION. IF YOU DO NOT AGREE WITH THE TERMS OF USE, PLEASE DO NOT USE THE APPLICATION. These Terms of Use will be effective immediately upon Your acceptance of Our terms and conditions, Your use of Our Application being indicative of such acceptance. These Terms of Use shall be enforceable, in the same manner as any other written agreement."
      },
      {
        "type": "p",
        "text": "2.9. You agree that the Company may revise, modify, add, or remove portions of these Terms of Use from time to time by updating and uploading the same on the Application and You agree to abide by and be bound by such Terms of Use. Your continued use of the Application affirms Your consent to accept any new or revised Terms of Use. We encourage You to check the Application periodically to ensure that You are aware of the latest Terms of Use."
      },
      {
        "type": "p",
        "text": "2.10. The content on the Application is provided for general information only. It is not intended to amount to advice on which you should rely. You must obtain professional or specialist advice before taking, or refraining from taking, any action on the basis of the content on the Application."
      },
      {
        "type": "h3",
        "text": "3. AMENDMENT"
      },
      {
        "type": "p",
        "text": "3.1. The Company reserves the right to modify the Application and/or alter these Terms of Use and/or Policies (“User Agreement”) at any time and retains the right to deny access at any time including the deletion of the account, to anyone who the Company believes has violated the provisions of the User Agreement."
      },
      {
        "type": "p",
        "text": "3.2. You are advised that any amendment to the User Agreement incorporated herein by reference will only be notified on the Application on publicly accessible links and You agree by accessing, browsing or using the Application that such publication shall immediately constitute sufficient notice for all purposes against You. The revised version/ terms shall be effective from the time that the Company publishes the same on the Application."
      },
      {
        "type": "p",
        "text": "3.3. The Company shall not be liable to give any prior notice to the Users for any amendments to the User Agreement, which in the opinion of the Company, has the effect of diminishing the User’s existing rights or imposing additional obligations. You understand and hereby accept that the decision, whether any proposed amendments to the User Agreement have the effect of diminishing the User’s existing rights or imposing additional obligations on the User, shall be decided by the Company in its sole discretion."
      },
      {
        "type": "h3",
        "text": "4. ELIGIBLITY"
      },
      {
        "type": "p",
        "text": "4.1. In order to use the Application, You need to be 18 (eighteen) years of age or older. The Application may only be used or accessed by such persons who can enter into and perform legally binding contracts under Indian Contract Act, 1872."
      },
      {
        "type": "p",
        "text": "4.2. The Company shall not be liable in case any false information is provided by the User or in case of any misrepresentation by the User, including with regards the User’s age and the User and/or his natural or appointed guardian alone shall be liable for the consequences as per the Applicable Law."
      },
      {
        "type": "p",
        "text": "4.3. The Company disclaims all liability arising out of such unauthorized use of the Application and any third-party liability arising out of Your use of the Application if You are a minor."
      },
      {
        "type": "h3",
        "text": "5. MARKETING"
      },
      {
        "type": "p",
        "text": "You confirm and acknowledge that Company is authorized to send updates and information to its Users, through emails, phone calls, short message service or other electronic and non-electronic mode of communication, and no such communication shall be deemed to be unsolicited commercial communication and / or in violation of any Applicable Laws."
      },
      {
        "type": "h3",
        "text": "6. PROHIBITED USE"
      },
      {
        "type": "p",
        "text": "The Application may be used only for lawful purposes. Company specifically prohibits any use of the Application for, and You agree not to use the Application for, any unlawful and / or fraudulent purposes, including but not limited to the following purposes:"
      },
      {
        "type": "p",
        "text": "6.1. Modifying, publishing, storing, transmitting, distributing, displaying, performing, participating in the transfer or sale of, create derivative works on, or in any way exploiting, any of the copyrighted/copyrightable material contained on the Application, in whole or in part, without Our prior written consent."
      },
      {
        "type": "p",
        "text": "6.2. Defame, libel, disparage, threaten, harass or intimidate anyone or otherwise violate the personal, privacy, contractual, intellectual property or other rights of any person, including by the use of offensive comments related to race, national origin, gender, sexual preference or physical handicap."
      },
      {
        "type": "h3",
        "text": "7. SECURITY"
      },
      {
        "type": "p",
        "text": "7.1. You are prohibited from violating or attempting to violate the security of the Application, including, without limitation:"
      },
      {
        "type": "p",
        "text": "7.1.1. attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization,"
      },
      {
        "type": "p",
        "text": "7.1.2. interfere with service to any user, host, or network."
      },
      {
        "type": "p",
        "text": "7.2. You shall not misuse this Application by knowingly introducing viruses, trojans, worms, logic bombs or other materials that are malicious or technologically harmful (together “Viruses”). You must not attempt to gain unauthorized access to Our Application, the server on which the Application is stored or any server, computer or database connected to this Application. You must not attack this Application via a denial-of-service attack. Further, You shall not interfere with or circumvent any security feature of the Application or any feature that restricts or enforces limitations on use of or access to the Application, such as probing or scanning the vulnerability of any system, network or breach."
      },
      {
        "type": "p",
        "text": "7.3. By breaching the provisions of this Clause, You may be liable to be prosecuted under the Act and any other Applicable Law. We will report any such breach to the relevant law enforcement authorities and We will co-operate with such authorities by disclosing Your identity to them. In the event of such a breach, Your rights to use this Application will cease immediately. 7.4. We will not be liable for any loss or damage caused by a denial-of-service attack or Viruses that may infect your computer equipment, computer programs, data or other proprietary material due to Your use of this Application or to Your downloading of any material posted on it, or on any Application linked to it."
      },
      {
        "type": "p",
        "text": "7.5. You agree to immediately report to Us all incidents involving suspected or actual unauthorized access, disclosure, alteration, loss, damage, or destruction of data."
      },
      {
        "type": "p",
        "text": "7.6. You shall not interfere with or disrupt (or attempt to interfere with or disrupt) access and enjoyment of the Application of other users or any host or network, including, without limitation, creating or transmitting unwanted electronic communications such as “spam” to other users, overloading, flooding or mail-bombing the Application, or scripting the creation of content in such a manner as to interfere with or create an undue burden on the Application."
      },
      {
        "type": "p",
        "text": "7.7. You are prohibited from reverse engineering, decompiling, reverse assembling, modifying or attempting to discover or copy any software, source code or structure that the Application utilize to generate web pages or any software or other products or processes accessible through the Application."
      },
      {
        "type": "h3",
        "text": "8. REPRESENTATIONS AND WARRANTIES"
      },
      {
        "type": "p",
        "text": "You hereby represent and warrant:"
      },
      {
        "type": "p",
        "text": "8.1. That You have the right, authority, and capacity to enter into these Terms of Use on Your own behalf and on behalf on any entity for whom You are acting and to abide by all of the terms and conditions contained herein, and that if any aspect of Your participation violates provisions of the law to which You are subject, You will cease using the Application and close Your account;"
      },
      {
        "type": "p",
        "text": "8.2. That You are at eligible and above the age of 18 (eighteen) years as per Applicable Laws;"
      },
      {
        "type": "p",
        "text": "8.3. That You shall not use a false name or email address owned or controlled by another person with the intent to impersonate that person or for any other reason;"
      },
      {
        "type": "p",
        "text": "8.4. That You shall comply with the terms and conditions stipulated in these Terms of Use;"
      },
      {
        "type": "p",
        "text": "8.5. That all the representations made by You to Us including in accordance with these terms and conditions are true, correct and complete and that You will update Your Information with the Company as needed so that it remains true, correct and complete;"
      },
      {
        "type": "p",
        "text": "8.6. That You will conduct yourself in a professional manner in all Your interactions with any other User, Company, their respective members, employees and officers and shall not defame, harass, intimidate, threaten, disparage, libel or otherwise make false statement concerning any of the aforesaid persons in the course of Your interactions with them or third parties."
      },
      {
        "type": "h3",
        "text": "9. INTELLECTUAL PROPERTY"
      },
      {
        "type": "p",
        "text": "9.1. This Application is operated by and is the sole property of the Company. Any and all material on this Application, including images, illustrations, trade names, proprietary information and knowledge, technology, databases, or rights with respect thereto necessary for Our business as is now being operated are protected by copyrights, trademarks, and other intellectual property rights that are owned by Us or by other parties that have licensed such material to Us, or such parties having ownership of content uploaded on the Application. You agree that any and all material displayed on the Application is solely for Your personal use and You shall not, whether directly or indirectly, copy, reproduce, republish, post, upload, transmit or distribute such material in any manner and through any media including by way of e-mail or other electronic means and You shall not assist any other person in doing so. Modification of the said materials or use of the materials on any other Application or networked computer environment or use of the materials for any purpose other than personal use is a violation of the said copyrights, trademarks and other intellectual proprietary rights, and is expressly prohibited. Application grants to You a temporary, non-exclusive, revocable, non-transferable limited license to use the Application for Your own use. All right, title, and interest in and to the Application (excluding content uploaded specifically by a User) is and will remain the exclusive property of Company and/or its licensors."
      },
      {
        "type": "p",
        "text": "9.2. You agree that these Terms of Use, do not entitle You to any support, upgrades, updates, add-ons, patches, enhancements, or fixes for the Application (for the purpose of this Clause 9.2, “Updates”). We may, however, occasionally provide automatic Updates to the Application at Our sole discretion (and without any advanced notification to You). Any such Updates shall become part of the services and subject to these Terms of Use."
      },
      {
        "type": "p",
        "text": "9.3. From time to time, we test various aspects of Our Application, including our Application, user interfaces, service levels, plans, features, availability of content, delivery, and pricing, and we reserve the right to include you in or exclude you from these tests without notice."
      },
      {
        "type": "h3",
        "text": "10. SYSTEM LIMITATIONS AND FAILURES"
      },
      {
        "type": "p",
        "text": "We use systems for providing You access to and facilitating Your use of the Application. These systems may encounter technical or other limitations, and computer and communications hardware systems might experience interruptions. Further, We continually enhance and improve these systems in order to accommodate the level of use of the Application. We may also add additional features and functionality to Application that might result in the need to develop or license additional technologies. Increased utilization of the Application or providing new features or functionality may cause unanticipated system disruptions, slower response times, degradation in levels of customer service, and delays in reporting accurate financial information. You agree that We shall not be liable to You or to any third party claiming through You, for any such failures contemplated herein."
      },
      {
        "type": "h3",
        "text": "11. PRIVACY AND CONFIDENTIALITY"
      },
      {
        "type": "p",
        "text": "11.1. Your use of the Application is governed by Our Privacy Policy, which can be located at [Please attach the privacy policy link here]."
      },
      {
        "type": "p",
        "text": "11.2. Please read Our Privacy Policy to understand Our information collection and usage practices. You may obtain certain confidential information, including without limitation, technical, contractual, pricing, activities and services, customer lists, knowledge of customer needs and preferences, business strategies, marketing strategies, methods of operation, markets and other valuable information that should reasonably be understood as confidential (“Confidential Information”). You acknowledge and agree to hold all Confidential Information in strict confidence. Title and all interests to all Confidential Information shall be vested in Us. Your obligations regarding Confidential Information will survive the termination of these Terms of Use. Upon such termination, You must stop forthwith using any Confidential Information to which You may have been exposed in due course of Your use of the Application."
      },
      {
        "type": "p",
        "text": "11.3. You agree that Your obligations under this Clause are necessary and reasonable in order to protect Our business and expressly agree that monetary damages would be inadequate to compensate for any breach of any covenant or agreement set forth herein. Accordingly, You agree and acknowledge that any such violation or threatened violation will cause irreparable harm and injury to Company and that, in addition to any other remedies that may be available, in law, equity or otherwise, Company shall be entitled to obtain injunctive relief against the threatened breach of the terms of this Clause or the continuation of any such breach."
      },
      {
        "type": "p",
        "text": "11.4. The restrictions in this Clause shall not apply to disclosure of Confidential Information by either party if and to the extent the disclosure is:"
      },
      {
        "type": "p",
        "text": "11.4.1. required by the Applicable Law of any jurisdiction,"
      },
      {
        "type": "p",
        "text": "11.4.2. required by any applicable regulatory or governmental body to which the relevant party is subject or submits, wherever situated, whether or not the requirement for disclosure has the force of law,"
      },
      {
        "type": "p",
        "text": "11.4.3. made to employees and representatives on a need to know basis, provided that such persons are required to treat such Information as confidential."
      },
      {
        "type": "h3",
        "text": "12. MONITORING"
      },
      {
        "type": "p",
        "text": "12.1. All electronic communications and content presented and/or passed to Us, may be monitored, examined, saved, read, transcribed, stored, or retransmitted in the course of daily operations by any duly authorized employee or agent of Company in the exercise of their duties, or by law enforcement authorities who may be assisting Company in investigating possible contravention / non-compliance with Applicable Law."
      },
      {
        "type": "p",
        "text": "12.2. Electronic communications and content may be examined by automated means."
      },
      {
        "type": "p",
        "text": "12.3. Company has the right to reject, at its sole discretion, from the Application any electronic communications or content deemed not to be in compliance with the corporate policies and procedures of Company."
      },
      {
        "type": "h3",
        "text": "13. FOREIGN JURISDICTION"
      },
      {
        "type": "p",
        "text": "The Company makes no representation that the content contained on the Application is appropriate or to be used or accessed outside of the Republic of India. You are expressly notified that foreign countries have their own regulations that must be observed in relation to Your use or access of the Application. You must make your own assessment regarding, and are responsible for compliance with, regulatory requirements as may be applicable to Your use and access of the Application in such jurisdictions."
      },
      {
        "type": "h3",
        "text": "14. GRIEVANCE REDRESSAL"
      },
      {
        "type": "p",
        "text": "14.1 In order to address any of Your grievances and / or discrepancies of the information displayed on the Application, Company shall designate the below mentioned grievance redressal officer(s). The Grievance Officer shall redress all the grievances expeditiously as per the mechanism provided in its Consumer Grievance Redressal Policyand no later thanone (1) month from the date of receipt of the grievance, as provided under the Act."
      },
      {
        "type": "p",
        "text": "Name: **Avinash Rai**"
      },
      {
        "type": "p",
        "text": "Email: **info@skillcase.info**"
      },
      {
        "type": "p",
        "text": "14.2 Dispute Resolution: Any dispute relating in any way to Your visit to the Company’s website, use and download of the Application or to Services through the Application shall be submitted to arbitration by a sole arbitrator mutually appointed by the parties, atBengaluru, India, except that, to the extent You have in any manner violated or threatened to violate the Company’s intellectual property rights, We may seek injunctive or other appropriate relief. The arbitration under these Terms of Use shall be in accordance with the provisions of the Indian Arbitration and Conciliation Act, 1996. The language of arbitration proceedings shall be English. The Award shall be final and binding on the parties."
      },
      {
        "type": "p",
        "text": "14.3 To the fullest extent permitted by applicable law, no arbitration under this agreement shall be joined to an arbitration involving any other party subject to this agreement, whether through class arbitration proceedings or otherwise."
      },
      {
        "type": "p",
        "text": "14.4 Governing Law. These Terms of Use shall be governed by and construed in accordance with the laws of Republic of India."
      },
      {
        "type": "p",
        "text": "14.5 Jurisdiction. Subject to the above grievance redressal mechanism provided by the Company and arbitration clause, the competent courts at Bengaluru shall have exclusive jurisdiction over all matters arising from these Terms of Use."
      },
      {
        "type": "h3",
        "text": "15. Refunds"
      },
      {
        "type": "p",
        "text": "15.1 Refunds, where applicable, will be processed to the original payment method used at the time of purchase."
      },
      {
        "type": "p",
        "text": "15.2 Refund requests must be made in accordance with the Company’s refund policy as published on the Application or Website."
      },
      {
        "type": "p",
        "text": "15.3 Once approved, refunds will be initiated within 5 (five) business days and may take an additional 7–10 (seven to ten) business days to reflect in your account, depending on your bank or payment provider."
      },
      {
        "type": "p",
        "text": "15.4 The Company is not responsible for delays caused by payment gateway providers, banks, or other external factors beyond its control."
      },
      {
        "type": "p",
        "text": "15.5 No refunds will be provided for services already availed or for subscription periods that have commenced, except as required by applicable law."
      },
      {
        "type": "h3",
        "text": "16. LIMITATION OF LIABILITY"
      },
      {
        "type": "p",
        "text": "In no event will the Company, its Affiliates, suppliers or licensors, be liable with respect to any subject matter of these Terms of Use under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the subscription fee (if any) paid by You to the Company in the three (3) month period prior to the cause of action. The Company shall have no liability for any failure or delay due to matters beyond or not within their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law."
      },
      {
        "type": "h3",
        "text": "17. INDEMNITY FOR NON-COMPLIANCE OR BREACH"
      },
      {
        "type": "p",
        "text": "You shall indemnify and hold harmless the Company and the Company's parent, subsidiaries, its Personnel, Affiliates, service providers and their respective officers, shareholders, directors, agents, and employees, from and against any and all Losses, liabilities, actions, suits, claims, proceedings, costs, damages, judgments, amounts paid in settlement and expenses (including without limitation attorneys' fees and disbursements) (“Losses”), made by any third party or penalty imposed due to or arising out of Your breach of the User Agreement or resulting from untrue, inaccurate, misleading not current or incomplete information provided or verified by You."
      },
      {
        "type": "h3",
        "text": "18. DISCLAIMER"
      },
      {
        "type": "p",
        "text": "18.1. THE SERVICE THROUGH THE APPLICATION OF THE COMPANY IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. USE OF THE SERVICE IS AT PROPERTY OWNER’S SOLE RISK. THE COMPANY DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR FREE, NOR DOES COMPANY MAKE ANY WARRANTY AS TO ANY RESULTS THAT MAY BE OBTAINED BY USE OF THE SERVICE. THE COMPANY MAKES NO OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, IN RELATION TO THE SERVICE. 18.2. THE COMPANY SHALL NOT BE LIABLE OR RESPONSIBLE FOR ANY AND ALL LOSSES CAUSED TO ANY USER ON ACCOUNT OF ANY MISREPRESENTATION OR FRAUD ON PART OF THE RECRUITERS. THE COMPANY IS MERELY CONNECTING THE USER TO RECRUITERS THROUGH ITS APPLICATION.THE COMPANY TAKES NO RESPONSIBILITY WITH RESPECT TO THE JOBPOSTED IN THE APPLICATION. THE USER AGREE AND ACKNOWLEDGE THAT, AND THE USER FURTHER AFFIRMS THAT, THE USER SHALL BE SOLELY RESPONSIBLE TO THE USER FOR ANY LOSSES THAT MAY BE CAUSED ON ACCOUNT OF THE JOBS SECURED THROUGH THE APPLICATION. THE USER AGREES THAT THE COMPANY IS MERELY A FACILITATOR AND THE USER SHALL HOLD THE COMPANY HARMLESS AGAINST ALL LOSSES."
      },
      {
        "type": "p",
        "text": "18.3. THE DOCUMENTS AND GRAPHICS ON THIS APPLICATION COULD INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. THE COMPANY MAY MAKE IMPROVEMENTS AND/OR CHANGES HEREIN AT ANY TIME. THE COMPANY MAKES NO REPRESENTATIONS ABOUT THE ACCURACY OF THE INFORMATION CONTAINED IN THE DOCUMENTS AND GRAPHICS ON THIS APPLICATION FOR ANY PURPOSE. ALL DOCUMENTS AND GRAPHICS ARE PROVIDED “AS IS” AND “AS AVAILABLE”. THE COMPANY HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR ANY PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT, THE COMPANY AND/OR THEIR LICENSORS/ SUPPLIERS SHALL BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL DAMAGES FOR ANY USE OF THE APPLICATION, THE INFORMATION, OR ON ANY OTHER HYPERLINKED WEB SITE, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR OTHER DATA ON THE RECRUITER INFORMATION HANDLING SYSTEM OR OTHERWISE, EVEN IF THE COMPANY IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES."
      },
      {
        "type": "p",
        "text": "18.4. THE COMPANY DOES NOT GUARANTEE THAT ANY CONTENT, INFORMATION, SOFTWARE OR OTHER MATERIAL ACCESSIBLE THROUGH THE APPLICATION WILL BE FREE OF VIRUSES, “WORMS”, “TROJAN HORSES”, OR THEIR HARMFUL COMPONENTS."
      },
      {
        "type": "h3",
        "text": "19. RISK DISCLOSURE"
      },
      {
        "type": "p",
        "text": "19.1. No advice. The Company does not provide or offer any advice whatsoever. No information or knowledge provided on the Application shall be construed and / or interpreted as such advice. No person and / or entity, under any circumstances, should make any decision(s) based solely on the information provided on the Application."
      },
      {
        "type": "p",
        "text": "19.2. No representations. The Company makes no representation, warranty and / or guarantee as to the quality, accuracy, completeness, performance, or fitness of information, advice, tool, calculator, analysis, report, data, content news, price, statistic, comment, feedback, etc., provided on, or through the Application. The information, reports and services are dependent on various assumptions, individual preferences, and other factors."
      },
      {
        "type": "p",
        "text": "19.3. Risk on forward – looking terms. The Users understand and acknowledge that past performance is not indicative of future results and there can be no assurance that the arrangement described on the Application will achieve its goals. Certain information contained herein constitutes “forward looking statements” which can be identified by the use of forward-looking terminology, because of various risks and uncertainties, actual events or results or actual performance may differ materially from the events, results or performance reflected or contemplated in such forward-looking statements. As a result, the Property Owner should not rely on such forward-looking statements."
      },
      {
        "type": "p",
        "text": "19.4. Risk on Transactions."
      },
      {
        "type": "p",
        "text": "19.4.1. The Company only provides technological services to the Users, without providing any advice, direction or undertaking any management."
      },
      {
        "type": "p",
        "text": "19.4.2. The Company only acts as a facilitator and connects User to the recruiters."
      },
      {
        "type": "p",
        "text": "19.4.3. The Company does not guarantee any job offers."
      },
      {
        "type": "h3",
        "text": "20. MISCELLANEOUS"
      },
      {
        "type": "p",
        "text": "20.1. Assignment. You cannot assign or otherwise transfer Your rights or obligations under these Terms of Use to any affiliate and / or third party without the prior consent of Company. 20.2. Severability. If any provision of these Terms of Use is held to be illegal, invalid, or unenforceable under any present or future Applicable Law (a) such clause or part thereof shall be fully severable; and (b) the remaining provisions of these Terms of Use shall remain in full force and effect and shall not be affected by the illegal, invalid, or unenforceable provision or by its severance here from to the extent permissible under Applicable Law."
      },
      {
        "type": "p",
        "text": "20.3. Notices. All notices and other communications required or permitted hereunder to be given to a party will be in writing, in the English language, and will be sent by way of e-mail addressed to such party’s address as set forth below."
      },
      {
        "type": "p",
        "text": "For Company: **info@skillcase.info**"
      },
      {
        "type": "p",
        "text": "For User: Such email address contained under the Information."
      },
      {
        "type": "p",
        "text": "20.4. Changes to Terms of Use. Company reserves the right to update (change, modify, add and/or delete) these Terms of Use from time to time, at the sole discretion of Company. The changes will reflect company initiatives, changes in the law or technology or changes in Company practices. When We update these Terms of Use, We will intimate you of the amendments on Your email address and / or on the Application. If you do not agree to the amendments, please do not use the Application any further. Your continued use of the Application following the posting of changes will mean that You accept and agree to the revisions."
      },
      {
        "type": "p",
        "text": "20.5. Indemnity. The User agrees to indemnify and hold harmless Company, its Affiliates, third – parties associated with Company and their respective shareholders, officers, directors, agents, and employees, from any losses, liabilities, damages, costs and expenses, claims or demand, made by any third party arising out of; (a) the User’s breach or non-performance of the terms of these Terms of Use or,"
      },
      {
        "type": "p",
        "text": "(b) the User’s violation of any Applicable Laws or,"
      },
      {
        "type": "p",
        "text": "(d) the rights of a third party."
      }
    ]
  },
  "privacy": {
    "title": "Privacy Policy",
    "eyebrow": "Data protection",
    "sourceUrl": "https://skillcase.in/privacy-policy",
    "blocks": [
      {
        "type": "h1",
        "text": "Privacy Policy"
      },
      {
        "type": "h1",
        "text": "PRIVACY POLICY"
      },
      {
        "type": "h3",
        "text": "1. DEFINITIONS"
      },
      {
        "type": "p",
        "text": "1.1 **“Act”** means Information Technology Act, 2000 and any amendments thereof;"
      },
      {
        "type": "p",
        "text": "1.2 **“Applicable Law(s)”** means all statutes, enactments, acts of legislature or parliament, ordinances, rules, bye-laws, regulations, notifications, policies, directions, directives and orders as such are in effect as of the date hereof or as may be amended, modified, enacted or revoked from time-to-time hereafter or other governmental restrictions or any similar form of decision of, or determination by any government, statutory authority, tribunal, board, court having jurisdiction over the matter in question in India;"
      },
      {
        "type": "p",
        "text": "1.3 **“Application”** refers to the web portal (www.skillcase.in) by means of which the Company makes its services available;"
      },
      {
        "type": "p",
        "text": "1.4 **“Business Partner(s)”** shall mean such entities that We have a business partnership with, as updated from time to time;"
      },
      {
        "type": "p",
        "text": "1.5 **“Consent”** shall mean as per Clause (III) of the Privacy Policy;"
      },
      {
        "type": "p",
        "text": "1.6 **“Database”** shall mean an organized collection of structured information, or data, that is stored electronically in Our computer systems."
      },
      {
        "type": "p",
        "text": "1.7 **“Log Data”** shall include internet protocol address, browser type, browser language, referring URL, files accessed, errors generated, time zone, operating system and other visitor details collected in Our log files, the pages of our App that You visit, the time and date of Your visit, the time spent on those pages/ and other statistics;"
      },
      {
        "type": "p",
        "text": "1.8 **“Purpose” **includes [●]"
      },
      {
        "type": "p",
        "text": "1.9 **“Personal Information”** shall mean information such as (a) Name of the User; (b) Contact Number, (c) Location of the User, as provided by the User, (g) PAN details, and (h) such other information of the User, as and when collected;"
      },
      {
        "type": "p",
        "text": "1.10 **“Privacy Policy”** shall mean this document that governs usage of data by Us."
      },
      {
        "type": "p",
        "text": "1.11 **“Rules”** means the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011;"
      },
      {
        "type": "p",
        "text": "1.12 **“User”**, or **“You”**, or **“Your”** shall refer any person or a person representing an entity under the laws of India that accesses the App;"
      },
      {
        "type": "p",
        "text": "1.13 **“User Data”** shall mean the cumulative data obtained by Us, from User activity on the Application;"
      },
      {
        "type": "h3",
        "text": "2. PRIVACY POLICY"
      },
      {
        "type": "p",
        "text": "2.1 This privacy policy (“Privacy Policy”) governs Your use of the Our App, as we endeavor to provide Users with Our Services including to create and maintain an Application for listing of [●]. (“Services”)."
      },
      {
        "type": "p",
        "text": "2.2 This Privacy Policy has been duly framed in accordance with the Act and the Rules to ensure maximum protection to the information provided by You. This electronic record is generated by a computer system and does not require any physical or digital signatures."
      },
      {
        "type": "p",
        "text": "2.3 We, (“Skillcase Education Private Limited”) have Our registered office at **#1207/343 & 1207/1/343/1, 9th Main, 7th Sector, HSR Layout, Bangalore, Bangalore South, Karnataka, India, 560102** bearing **CIN U85499KA2024PTC185038** (hereinafter referred to as “We”, “Us”, “Company” or “Our” which expression shall mean and include its affiliates, successors and permitted assigns), wherein We affirm that this Website and App are solely owned by Us."
      },
      {
        "type": "p",
        "text": "2.4 By registering on Our App, You agree to abide by the terms and conditions pertaining to collection, retention, and use of information set forth in this Privacy Policy. If You do not agree to the Privacy Policy, You may refrain from registering on the App and in this case, We will be unable to provide you with Our Services."
      },
      {
        "type": "p",
        "text": "2.5 This Privacy Policy provides You with details about the manner in which Your data is collected, stored and used by Us. You are advised to read this Privacy Policy carefully. By Browsing Our Application, You expressly give Us consent to use and disclose Your Personal Information in accordance with this Privacy Policy, wherever necessitated. If You do not agree with the terms of the Privacy Policy, please do not use or avail Our Services through Our Application."
      },
      {
        "type": "p",
        "text": "2.6 Company is not targeted towards minors. The target audience and content thereof shall be targeted towards adults who are above the above of 18 (Eighteen). In the event the Application has been accessed and / or any Personal Information has been inadvertently collected from a person / minor not eligible as per this clause, kindly contact the Company at info@skillcase.info and the Company shall delete such Personal Information (defined below) as soon as possible."
      },
      {
        "type": "h3",
        "text": "3. CONSENT OF USER"
      },
      {
        "type": "p",
        "text": "3.1 If You are a business entity, You warrant and represent that You are accessing the Application for business or related purposes only and the entity holds valid registrations for the relevant statutory authority, where applicable."
      },
      {
        "type": "p",
        "text": "3.2 If the User is accessing the Application on behalf of, a corporate entity, User warrants and represents that User has requisite authority to bind that corporate entity and that User is duly authorized by the business entity to accept the Privacy Policy and User has the authority to bind that business entity to the Privacy Policy."
      },
      {
        "type": "p",
        "text": "3.3 If the User is a natural person, he/she is above the age of 18 (eighteen) and is eligible under the Indian Contract Act, 1872 to enter into a valid agreement and be bound by the terms of this Privacy Policy."
      },
      {
        "type": "p",
        "text": "3.4 You acknowledge that Your Consent is being obtained for the Purpose defined under Clause 1 (7) above."
      },
      {
        "type": "p",
        "text": "3.5 ACCESSING, BROWSING OR OTHERWISE USING THE APPLICATION INDICATES YOUR ACCEPTANCE OF ALL THE TERMS IN THIS PRIVACY POLICY. PLEASE READ THE PRIVACY POLICY CAREFULLY BEFORE PROCEEDING. YOU DECLARE YOUR WILLINGNESS TO ABIDE AND BE BOUND BY THS PRIVACY POLICY THROUGH YOUR USE OF THE APPLICATION AND/ OR WEBSITE. IF YOU DO NOT AGREE WITH THE TERMS OF USE, PLEASE DO NOT USE THE APPLICATION. This Privacy Policy will be effective immediately upon Your acceptance of Our Privacy Policy, Your use of Our Application being indicative of such acceptance. This Privacy Policy shall be enforceable, in the same manner as any other written agreement."
      },
      {
        "type": "h3",
        "text": "4. POINTS OF DATA COLLECTION"
      },
      {
        "type": "p",
        "text": "4.1 Company receives information only when the Users enter their Personal Information on the Application."
      },
      {
        "type": "p",
        "text": "4.2 We collect information from Users when Users register with Us, through Our Application. Further, in cases where You are looking to avail Our Services, we may ask You to provide Your Personal Information such as a phone number for verification and your Personal Information. In case You are providing information to Us, on behalf of another person, You should only do so, if You are duly authorised by them under Applicable Laws."
      },
      {
        "type": "p",
        "text": "4.3 We may may also request Personal information during the course of provision of Our Services, to provide the You with other benefits of Our Services."
      },
      {
        "type": "h3",
        "text": "5. COLLECTION OF INFORMATION"
      },
      {
        "type": "p",
        "text": "**In order to provide Our Services, We may collect the following types of information:**"
      },
      {
        "type": "p",
        "text": "5.1 User information – When You use Our Application, We automatically receive and record information from Your device. Such information may include, location of Your device, Your device storage, Your IP address, cookie information, software and hardware attributes, unique device ID etc. Most of the information We collect during Your use of Our Application, is Your device and hardware IDs and device type, and basic usage stats about Your device and general use of Our Services does not by itself identify You to Us, though it may be unique or consist of or contain information that You consider personal. Specifically, We collect, retain and use information collected, retained and shared through Facebook Platform, Twitter, Google and YouTube, according to the applicable terms and conditions of their privacy policies."
      },
      {
        "type": "p",
        "text": "5.2 Personal Information and Database – On the basis of Your usage of Our App we may also export Your Personal Information from Our Database to any other third -party as permitted under Applicable Law (collectively referred to as “User Data”)."
      },
      {
        "type": "p",
        "text": "5.3 Registration – In order to avail Our Services, You shall have to register yourself on Our App. We shall record Your Personal Information and other information about You as furnished by You onto the App."
      },
      {
        "type": "p",
        "text": "5.4 User history and preferences – We save Your query terms as well as Your statement of experience with us. These may be associated with the unique registration ID of Your device. We also save Your recommendations and preferences for Our Services, as recorded through Your use of the Services and use them for personalization features."
      },
      {
        "type": "p",
        "text": "5.5 Cookies – When You use Our App, We may send one or more cookies. “Cookies” are small files placed on your hard drive that assist us in providing Our Services. Cookies can also help us provide information that is targeted to your interests. Most cookies are “session cookies,” meaning that they are automatically deleted from your storage at the end of a session."
      },
      {
        "type": "p",
        "text": "5.6 We use cookies to improve the quality of Our Application and Services by storing User preferences and tracking User information. Cookies shall have limited scope, either for the purpose of User enrolment/registration for imparting Services. You are always free to decline our cookies if Your mobile application permits, although in that case You may not be able to use certain features of the same."
      },
      {
        "type": "p",
        "text": "Additionally, you may encounter “cookies” or other similar devices on certain pages of the Application that are placed by third parties. We do not control the use of cookies by third parties."
      },
      {
        "type": "h3",
        "text": "6. USE OF INFORMATION"
      },
      {
        "type": "p",
        "text": "6.1 We collect Personal Information primarily for the Purpose as defined in Clause 1 (8) and to enable us to provide Our Services to You or help you browse Our Application, seamlessly."
      },
      {
        "type": "p",
        "text": "6.2 The Personal Information We collect allows Us to keep You posted on latest job openings, related to Your profile, security alerts and support and administrative messages, that You have specifically requested for. It also helps Us to improve Our Services. If You do not want to be on Our mailing list, You can opt out at any time by unsubscribing to Us, through the usage of Your mail ID."
      },
      {
        "type": "p",
        "text": "6.3 From time to time, We may use Your Personal Information to send important notices, such as communications and changes to Our Terms of Use or Privacy Policy. Since, this information is important to Your interaction with Us, You may only opt out of the same, only after communicating with Us or choosing to delete Your profile with Us. We may also use Personal Information for internal purposes such as data analysis and research to improve Our Services, products and customer communication."
      },
      {
        "type": "p",
        "text": "6.4 We may also collect information about You through other methods, including research surveys or information We obtain from third parties, including verification services, data services, as well as public sources. We shall not be responsible for any breach of privacy, or any issues related to accuracy of such third party data or third party information."
      },
      {
        "type": "h3",
        "text": "7. SHARING"
      },
      {
        "type": "p",
        "text": "We only share Personal Information with other companies or individuals in the following limited circumstances:"
      },
      {
        "type": "p",
        "text": "7.1 We may share with third parties the demographic location of Your device and Personal Information in order to provide the Service, improve and personalize Your experience of Our Service."
      },
      {
        "type": "p",
        "text": "7.2 We may share with third parties certain pieces of non-personal information, such as the number of Users who are using Our Services, users who clicked on a particular advertisement or who skipped a particular advertisement, as well as similar aggregated information. Such information does not identify You individually."
      },
      {
        "type": "p",
        "text": "7.3 We provide such information to trusted businesses or persons for the purpose of processing Personal Information and or other information on Our behalf. We require that these parties agree to process such information based on Our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality and security measures."
      },
      {
        "type": "p",
        "text": "7.4 Advertisers: We allow advertisers and/or merchant partners (“Advertisers”) to choose the demographic information of Users who will see their advertisements and/or promotional offers and You agree that We may provide any of the information We have collected from You in non-personally identifiable form to an Advertiser, in order for that Advertiser to select the appropriate audience for those advertisements and/or offers."
      },
      {
        "type": "h3",
        "text": "8. SECURITY"
      },
      {
        "type": "p",
        "text": "8.1 The security of Your Personal Information and User Data is important to Us. We take precautions, including administrative, technical and physical measures, to safeguard Your Personal information against loss, theft and misuse, as well as against unauthorized access, disclosure, alteration and destruction. Any Personal Information obtained by Us on Our Application shall be encrypted. Our Application has various electronic, procedural and physical security measures in place to protect the loss, misuse and alteration of information, or any accidental loss, destruction or damage to data. When You submit Your information, Your information is protected through Our security systems."
      },
      {
        "type": "p",
        "text": "8.2 In order to ensure the security of Your Personal Information, the Application employs various security measures. The Application uses https along with TLS certification for all communication between Our servers and User’s device. All Personal Information are encrypted in the Company’s servers to ensure that the Personal Information collected is secure from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss."
      },
      {
        "type": "p",
        "text": "8.3 It is expressly stated that the Application shall not be responsible for any breach of security or for any action of any third parties that receive Users’ personal data or events that are beyond the reasonable control of the Application or Company including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc."
      },
      {
        "type": "h3",
        "text": "9. STORAGE OF DATA"
      },
      {
        "type": "p",
        "text": "9.1 We will store Your Personal Information and User Data which shall be retained up to such period wherein such information is necessary to be stored and for such time period as may be permissible under Applicable Laws. In the event You terminate your Services with Us, Your express consent to this Privacy Policy, shall be understood as withdrawn."
      },
      {
        "type": "p",
        "text": "9.2 In the event You decide to stop availing Services, including but not limited to, deleting the Personal Information stored with Us, the same shall be honored by Us, if requested in writing to info@skillcase.info. In the event You wish to delete the Personal Information stored with Us, the same shall be honored by Us if requested in writing to info@skillcase.info. Any Personal Information deleted by the Company shall not be available to restore under any circumstances."
      },
      {
        "type": "p",
        "text": "9.3 We will keep records of communications, including but not limited to, phone calls received and made for making enquiries, orders, feedback and / or any other purposes for rendering Services effectively and efficiently. We shall be the exclusive owner of such data and records."
      },
      {
        "type": "p",
        "text": "9.4 As a rule, all records are regarded as confidential. Therefore, will not be divulged to any third party, unless required as per the terms of this Privacy Policy or under Applicable Laws."
      },
      {
        "type": "h3",
        "text": "10. PROTECTION OF CHILDREN"
      },
      {
        "type": "p",
        "text": "Use of Our Services is available only to persons who can form a legally binding contract under the relevant local laws applicable to Your country. If you are a User under the age of 18 (“Child User”), You may use Our Services only with the involvement of a parent or guardian. Please ensure that You have adequate consent from Your parent or guardian to access Services in accordance with the present Privacy Policy."
      },
      {
        "type": "p",
        "text": "If You are the parent or guardian of a Child User, please advise Your child of the risks of posting Personal Information in order to avail Our Services or other online services, and that any information posted may be used by third parties without restriction. Notwithstanding anything contained herein, We shall always presume that every User has adequate consent and free-will to access Services and to enter into a legally enforceable contract with Us."
      },
      {
        "type": "p",
        "text": "We also reserve the right to remove, at Our sole discretion, any content or material posted by a User which may be of defamatory or sexual nature or offensive to other Users in any manner, and take appropriate legal action against such User."
      },
      {
        "type": "h3",
        "text": "11. MECHANISM OF SHARING DATA WITH THIRD PARTIES"
      },
      {
        "type": "p",
        "text": "11.1 We disclose Personal Information about You to recruiters. We also reserve the right to disclose your Personal Information to recruiters. We provide Your Personal Information to our Business Partners, representatives and third party processors to administer and process for the Purposes notified to you in this Privacy Policy, and We may also share such details with third parties, including but not limited to, auditors or legal advisors to obtain professional advice. Any such processing will be governed by an agreement in the form required as per Applicable Law, preserving any and all of Your statutory data protection rights. You authorise Us to exchange, transfer, share, part with all or any of your Personal Information, across borders and from Your country to any other countries across the world with our recruiters/affiliates/agents/third party service providers and partners for the Purposes specified under this Privacy Policy or as may be required by Applicable Law."
      },
      {
        "type": "p",
        "text": "11.2 You acknowledge that We may be obligated by law to disclose and / or transfer your Personal Information with judicial and / or quasi – judicial courts and government agencies in certain instances such as for verification of identity or for prevention, detection, investigation, prosecution, and punishment for offences, or in compliance with Applicable Laws. In the event of any regulatory inquiry, including court issued warrants or written request from any agencies of the Government, supported by warrants, We shall have no option but to de-encrypt the Personal Information to the extent sought and share the same with such regulator or court or appropriate authority upon receiving specific warrant from such authority issued by a competent court. In such an event We shall not be liable in any way for such disclosure and We shall not be responsible to either inform Users or seek Users’ prior approval."
      },
      {
        "type": "p",
        "text": "11.3 Notwithstanding the above, we are not responsible for the confidentiality, security or distribution of Your Personal Information by third party (ies) outside the scope of our agreement with such third party (ies), in accordance with Clause (VI). We will not be responsible for any breach of security or for any actions of any third parties or events that are beyond Our reasonable control, including but not limited to, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, poor quality of internet service and / or telephone service of the User etc."
      },
      {
        "type": "p",
        "text": "11.4 We may share Your Personal Information with Our other corporate and/or associate entities and affiliates or government officials or law enforcement officials to; (a) help detect and prevent identity theft, fraud and other potentially illegal acts and cyber security incidents, to help protect the property and rights of Us or any other third party, or to protect the safety of the public or any person, or to prevent or stop any illegal activity, (b) help and detect co-related/related or multiple accounts to prevent abuse of our services."
      },
      {
        "type": "h3",
        "text": "12. PRINCIPLES FOR PROTECTION OF PRIVACY"
      },
      {
        "type": "p",
        "text": "12.1 Commitment to Privacy. The Application is strongly committed to Users’ right to privacy and to keeping Users’ Personal Information and Financial Information secure. To earn Users’ trust and confidence, we are fully disclosing our privacy practices. We encourage Users to read our Privacy Policy to understand what types of Personal Information we collect and how we use this information."
      },
      {
        "type": "p",
        "text": "12.2 Applicability. This Privacy Policy sets forth the reasonable security practices and procedures adopted by Us and shall apply to the use, disclosure and sharing Personal Information provided by the Users of the Application which is owned and operated by Us. This policy is equally applicable on the visiting Application for using Our Services. The Privacy Policy outlines the various measures undertaken by Us to provide Users with a convenient and safe online/ experience, while maintaining and safeguarding the confidentiality, integrity, and security of Users’ Personal Information, during storage and transmission through the world wide web. This Privacy Policy explains how We protect Personal Information provided by Users through the Application and how We store and use that information, to deliver the Services on the Application."
      },
      {
        "type": "p",
        "text": "12.3 Choice. You may choose whether / not to provide your Personal Information Us. If you choose not to provide the Personal Information the Application requests, you may still visit the Application, but you may be unable to access the Services. If you choose to have avail Our Services, We will naturally continue to contact you in connection with the said Services. We neither collect nor store your biometric information."
      },
      {
        "type": "p",
        "text": "12.4 Access/Accuracy To the extent that You do provide Us with Personal Information, We wish to maintain accurate, true and complete Personal Information. When We collect Personal Information from You, Our aim is to be able to reach out to You. You should keep Your information updated and correct. If for any reason Your information is inaccurate, You may send updates and corrections about Your Personal Information to Us, and We shall make reasonable efforts to incorporate the changes."
      },
      {
        "type": "p",
        "text": "12.5 Change in Policy. This Privacy Policy is subject to change at any time, and it is advised that Users review this Privacy Policy periodically. Any change to this Privacy Policy will become effective as soon as it is posted or linked to the revised Privacy Policy on the Application. Users shall receive a notification whenever there is a change in our Policy on Users’ registered email ID and the issuance of the notification shall constitute a fair amendment of the Privacy Policy."
      },
      {
        "type": "p",
        "text": "12.6 Retraction of User Consent. If at any time such changes are not agreeable to a User, then the User may terminate his registration with the Application, stop availing Our Services and usage of the Application. Such termination and / or stopping of further use shall not result in any automatic deletion of Users’ Personal Information already stored with Us and We take no responsibility or makes no representation which would imply otherwise. However, We can assure you that the User’s Personal Information will be deleted or ceased to be retained by Us within reasonable time as permitted under Applicable Laws."
      },
      {
        "type": "p",
        "text": "12.7 Users’ Responsibility. It shall be the responsibility of the Users to read and assess such changes in the Privacy Policy once such notifications have been sent to Users’ registered email ID."
      },
      {
        "type": "h3",
        "text": "13. NOTIFICATIONS"
      },
      {
        "type": "p",
        "text": "You may be contacted, by email or other messages; for example, We may send You promotional offers on behalf of other businesses, or communicate with You about Your use of the Service. Also, We may receive a confirmation when You open an email from Us. This confirmation helps Us improve Our service. If You do not want to receive email or other mail from Us, please indicate Your preference by clicking on the “Unsubscribe” link at the bottom of the email or changing Your email settings on Your account settings page. Please note that if You do not want to receive legal notices from Us, those legal notices will still govern Your use of the service, and You are responsible for reviewing such legal notices for changes."
      },
      {
        "type": "h3",
        "text": "14. PURGING OF PERSONAL INFORMATION"
      },
      {
        "type": "p",
        "text": "Users’ Personal Information may be stored with Us for a period of time after the User ceases to access or use Our Services for the purposes mentioned in this Privacy Policy as permitted under Applicable Laws and the same may be eventually erased / purged / removed from our Database by writing to us at info@skillcase.info."
      },
      {
        "type": "h3",
        "text": "15. RIGHT TO INJUNCTIVE RELIEF"
      },
      {
        "type": "p",
        "text": "It is acknowledged and admitted by the User that a breach of the Privacy Policy by the User can cause irreparable damage to Us, and such damages may or may not be entirely quantifiable in monetary terms. Therefore, in the event of a breach of this Privacy Policy by the User, the User acknowledges that We shall have a prima facie case and a favorable balance of convenience to seek an injunctive relief to stop such continuing breach from a court of competent jurisdiction."
      },
      {
        "type": "h3",
        "text": "16. LIMITATION OF LIABLITY"
      },
      {
        "type": "p",
        "text": "THE APPLICATION, AND OUR SERVICES ARE PROVIDED BY THE COMPANY ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. ALL WARRANTIES WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES AS TO NON-INFRINGEMENT, CORRESPONDENCE WITH DESCRIPTION, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXCLUDED TO THE FULLEST EXTENT PERMITTED BY LAW."
      },
      {
        "type": "p",
        "text": "NO LIABILITY ARISING OUT OF ANY VIOLATION OF DATA PRIVACY LAW IN ANY OTHER COUNTRY OTHER THEN REPUBLIC OF INIDA SHALL RESIDE WITH US. THE USERS OF SUCH COUNTRY (OTHER THAN REPUBLIC OF INDIA) NEED TO BE AWARE OF THE DATA PROTECTION LAWS OF THAT COUNTRY AND ACCORDINGLY ASSESS THE RISK SINCE THE COMPANY CLEARLY DISCLAIMS ALL RESPONSIBILITY RELATED TO PROTECTION OF SUCH DATA. WITHOUT LIMITING THE GENERALITY OF ABOVE CLAUSE, WE MAKE NO WARRANTY THAT (I) WE WILL MEET USERS’ REQUIREMENTS OR THAT USERS USE OF THE WEBSITE/APP, OR ACCESS TO THE SAME, WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE (II) THE QUALITY OF THE APP WILL MEET USERS’ EXPECTATIONS."
      },
      {
        "type": "p",
        "text": "WE SHALL NOT BE LIABLE FOR:-"
      },
      {
        "type": "p",
        "text": "i. ANY LOSS THAT USERS MAY INCUR AS A CONSEQUENCE OF UNAUTHORISED USE OF USERS ACCOUNT OR ACCOUNT INFORMATION;"
      },
      {
        "type": "p",
        "text": "ii. ANY INTERRUPTION OR NON-AVAILABILITY OF THE APP DURING PERIODIC MAINTENANCE OR FOR ANY OTHER REASON INCLUDING BUT NOT LIMITED TO SYSTEMIC FAILURES AND ACTS OF GOD;"
      },
      {
        "type": "p",
        "text": "iii. ANY INACCURACY, ERROR, OMISSION, INTERRUPTION, COMPLETENESS, DELETION, DEFECT, FAILURE OF PERFORMANCE, COMPUTER-VIRUS, COMMUNICATION LINE FAILURE, ALTERATION OF, OR ANY USE OF CONTENT HEREIN, REGARDLESS OF CAUSE, FOR ANY DAMAGES RESULTING THERE FROM; OR"
      },
      {
        "type": "p",
        "text": "iv. ANY LOSS OF OPPORTUNITY, GOODWILL OR REPUTATION; OR ANY INDIRECT OR CONSEQUENTIAL LOSS OR DAMAGE ARISING HOWSOEVER;"
      },
      {
        "type": "p",
        "text": "v. ACCURACY, CORRECTNESS OR ORIGINALITY OF ANY DATA INCLUDING ALL INDICES PUBLISHED ON THE APP WHETHER THE SAME IS THIRD PARTY DATA OR OTHERWISE."
      },
      {
        "type": "p",
        "text": "vi. ANY LOSS OF PROFITS, SALES, BUSINESS OR REVENUE; BUSINESS INTERRUPTION; LOSS OF ANTICIPATED SAVINGS; LOSS OF BUSINESS OPPORTUNITY, GOODWILL OR REPUTATION; OR ANY INDIRECT OR CONSEQUENTIAL LOSS OR DAMAGE HOWSOEVER ARISING."
      },
      {
        "type": "p",
        "text": "IN NO EVENT SHALL COMPANY, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS OR CONTRACTORS BE LIABLE FOR ANY COMPENSATORY, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, LOSS OF DATA, INCOME OR PROFIT, LOSS OF OR DAMAGE TO PROPERTY, OR ANY CLAIMS OF THE USERS OR OTHER THIRD PARTIES WHATSOEVER WITH RESPECT TO THE APPLICATION REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES THAT RESULT FROM ANY MISTAKE, OMISSION, VIRUS, DELAY OR INTERRUPTION IN OPERATION OR SERVICE OR FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM AN ACT OF GOD, COMMUNICATIONS FAILURE, THEFT OR OTHERWISE. THE COMPANY SHALL NOT BE LIABLE FOR ANY LOSSES OR DAMAGES WHATSOEVER RESULTING FROM ANY FAILURE OF THE INTERNET."
      },
      {
        "type": "p",
        "text": "THE COMPANY DOES NOT GUARANTEE THAT ANY CONTENT, INFORMATION, SOFTWARE OR OTHER MATERIAL ACCESSIBLE THROUGH THE APPLICATION OR THE WEBSITE WILL BE FREE OF VIRUSES, “WORMS”, “TROJAN HORSES”, OR THEIR HARMFUL COMPONENTS. THE COMPANY’S ENTIRE LIABILITY AND THE USER’S SOLE AND EXCLUSIVE REMEDY WITH RESPECT TO THE USE THE WEBSITE/APPLICATION IS TO CEASE USING THE SAME WITH IMMEDIATE EFFECT."
      },
      {
        "type": "p",
        "text": "USERS ACKNOWLEDGE THAT THE EXCLUSIONS AND LIMITATIONS ON OUR LIABILITY SET OUT IN THIS CLAUSE ARE DISTINCT AND SEPARATE PROVISIONS. IF ANY PROVISION OR PART-PROVISION OF THIS CLAUSE IS OR BECOMES INVALID, ILLEGAL OR UNENFORCEABLE, SUCH RESPECTIVE PROVISIONS SHALL BE SEVERED FROM THE PRIVACY POLICY AND THE PRIVACY POLICY SHALL BE READ WITHOUT SUCH UNLAWFUL PROVISIONS."
      },
      {
        "type": "h3",
        "text": "17. GREVIENCE REDRESSAL MECHANISM"
      },
      {
        "type": "p",
        "text": "In order to address any of Your grievances and / or discrepancies of the information displayed on the App, the App shall designate the below mentioned grievance redressal officer(s) (“Grievance Officer”). The Grievance Officer shall redress all the grievances expeditiously but within 1 (one) month from the date of receipt of the grievance as provided under the Act."
      },
      {
        "type": "p",
        "text": "• Grievance Redressal Officer – **Avinash Rai**"
      },
      {
        "type": "p",
        "text": "• Contact Information - **info@skillcase.info **"
      },
      {
        "type": "h3",
        "text": "18. INDEMNITY"
      },
      {
        "type": "p",
        "text": "Users shall indemnify, defend and hold Us harmless from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including attorney's fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Us that arise out of, result from, or may be payable by virtue of any breach or non-performance by Users of any of the terms of this Privacy Policy or of the Application."
      },
      {
        "type": "h3",
        "text": "19. DISCLAIMER"
      },
      {
        "type": "p",
        "text": "THE SERVICE IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. USE OF THE SERVICE IS AT USERS’ SOLE RISK. COMPANY DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR FREE, NOR DOES COMPANY MAKE ANY WARRANTY AS TO ANY RESULTS THAT MAY BE OBTAINED BY USE OF THE SERVICE. COMPANY MAKES NO OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, IN RELATION TO THE SERVICE."
      },
      {
        "type": "h3",
        "text": "20. GOVERNING LAW AND DISPUTE RESOLUTION"
      },
      {
        "type": "p",
        "text": "All disputes arising out of this Privacy Policy and any disclaimers on the Application shall be subject to the sole and exclusive jurisdiction of the courts of Bangalore, India."
      },
      {
        "type": "h3",
        "text": "21. CONTACT INFORMATION"
      },
      {
        "type": "p",
        "text": "If You have any questions or concerns with respect to this Policy any information contained on thereon, You may contact Us by writing to Us at info@skillcase.info. This Privacy Policy supersedes any previous versions."
      }
    ]
  }
} as const;
